### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by SilentWarrior1** [nuryads/vertyus#1]
Greetings!
```
------Account No.1------
Traceback (most recent call last):
  File "J:\Telegram\Vertus-main\Vertus.py", line 423, in <module>
    main()
  File "J:\Telegram\Vertus-main\Vertus.py", line 392, in main
    login(token)
  File "J:\Telegram\Vertus-main\Vertus.py", line 53, in login
    balance = int(data.get("user").get("balance"))/10**18
                  ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by SilentWarrior1** [comment]
the first one was solved (bad token)
but now i got this error after solving AD-task:
```
Vert Balance: 9.251 | Earned Offline: 0.0120
Farm Balance: 4.65252 | PPH: 0.2642
You have already claimed your daily reward today
Please wait 5 minutes
Traceback (most recent call last):
  File "J:\Telegram\Vertus-main\Vertus.py", line 423, in <module>
    main()
  File "J:\Telegram\Vertus-main\Vertus.py", line 397, in main
    task_ids, task_titles = get_task(token)
                            ^^^^^^^^^^^^^^^
  File "J:\Telegram\Vertus-main\Vertus.py", line 167, in get_task
    recommendations = data.get('recommendations', {}).get('missions', [])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
```
